repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: [--diff,  --check]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   additional_dependencies: [types-python-dateutil==2.8.19.10]
        id: mypy
        args: [--no-strict-optional, --ignore-missing-imports, --explicit-package-bases]